// =====================================================================
//  SITUAÇÕES DO JOGO
//  Cada situação tem:
//    cena      -> qual fundo usar: forja, escritorio, garagem, casa, quintal
//    titulo    -> nome curto
//    texto     -> o que está acontecendo
//    opcoes    -> 3 respostas. Cada uma tem:
//        texto      -> o que você faz
//        habilidade -> nome EXATO de uma habilidade de dados.js (a nota vem de lá)
//        sucesso    -> { vida, bateria, frase }  (o que muda se der certo)
//        falha      -> { vida, bateria, frase }  (o que muda se der errado)
//
//  Pra criar uma situação nova, copie um bloco inteiro e mude os textos.
// =====================================================================

const SITUACOES = [
  {
    cena: "escritorio",
    titulo: "A festa de 15 anos",
    texto: "Esther te chama pra festa de 15 anos da filha do tio da amiga dela do Crossfit. Você não conhece ninguém. Nem a amiga.",
    opcoes: [
      { texto: "Ficar na mesa de doces atendendo uma ligação que não existe", habilidade: "Preparação",
        sucesso: { vida: 0, bateria: +10, frase: "Três horas de 'alô? tá me ouvindo?'. Ninguém desconfiou. Comeu 14 brigadeiros." },
        falha:   { vida: 0, bateria: -15, frase: "O celular tocou de verdade no meio da encenação. A tia do Crossfit viu tudo." } },
      { texto: "Discursar como padrinho de uma menina que nunca viu", habilidade: "Oratória",
        sucesso: { vida: 0, bateria: +20, frase: "Chorou gente. A aniversariante te abraçou. Você ainda não sabe o nome dela." },
        falha:   { vida: 0, bateria: -20, frase: "Chamou a menina de Júlia. Ela se chama Isadora. O DJ cortou o microfone." } },
      { texto: "\"Forcei a coluna na forja\", com cara de dor ensaiada", habilidade: "Cutelaria",
        sucesso: { vida: +10, bateria: 0, frase: "Esther foi sozinha. Você forjou uma faca em paz e ainda ganhou um chá de camomila." },
        falha:   { vida: 0, bateria: -20, frase: "Esther lembrou que você carregou 40 kg de carvão ontem. Foi de gravata." } },
    ],
  },
  {
    cena: "garagem",
    titulo: "O Terios quebrou de novo",
    texto: "O Daihatsu apagou no meio da subida. De novo. O FuelTech pisca uma luz que nem o manual conhece.",
    opcoes: [
      { texto: "Abrir o capô e encarar o motor até ele confessar", habilidade: "Mecânica automotiva",
        sucesso: { vida: +15, bateria: 0, frase: "Era o terminal da bateria solto. Apertou com a mão. O Terios pegou de primeira, humilhado." },
        falha:   { vida: -15, bateria: 0, frase: "Encarou o motor por 40 minutos. O motor venceu. Guincho." } },
      { texto: "Cutucar o chicote com o alicate do EDC, método científico", habilidade: "Elétrica automotiva",
        sucesso: { vida: +10, bateria: 0, frase: "Achou o fio roído. Emenda de estrada, fita isolante, orgulho." },
        falha:   { vida: -20, bateria: 0, frase: "Cutucou o fio errado. Agora o limpador de para-brisa liga junto com a buzina." } },
      { texto: "Empurrar até em casa em silêncio, como quem já aceitou o destino", habilidade: "Resiliência",
        sucesso: { vida: +10, bateria: 0, frase: "Dois quilômetros de subida. Chegou suado, mas chegou. Treino de perna feito." },
        falha:   { vida: -10, bateria: 0, frase: "Na metade do caminho um vizinho parou pra ajudar. Empurrou 20 metros e desistiu." } },
    ],
  },
  {
    cena: "casa",
    titulo: "Hóspedes surpresa",
    texto: "A Rosa convidou \"umas pessoas\" pra dormir na sua casa. São sete. Você descobriu agora, pelo barulho das malas.",
    opcoes: [
      { texto: "Virar anfitrião e cozinhar pra sete desconhecidos", habilidade: "Culinária",
        sucesso: { vida: 0, bateria: +20, frase: "Fez um risoto que virou lenda. Um deles pediu a receita. Outro pediu pra morar." },
        falha:   { vida: 0, bateria: -10, frase: "Faltou arroz. Serviu ovo frito pra sete adultos às 23h. Silêncio na mesa." } },
      { texto: "Distribuir quartos e toalhas como quartel", habilidade: "Liderança",
        sucesso: { vida: 0, bateria: +10, frase: "Em 12 minutos todo mundo tinha cama, toalha e horário de banho. Eficiência assustadora." },
        falha:   { vida: 0, bateria: -15, frase: "Dois hóspedes brigaram pelo colchão inflável. Você dormiu no sofá. Na sua casa." } },
      { texto: "Trancar a forja e dormir abraçado na bigorna", habilidade: "Sobrevivência selvagem",
        sucesso: { vida: +15, bateria: 0, frase: "Melhor noite de sono do mês. A bigorna não ronca." },
        falha:   { vida: 0, bateria: -25, frase: "Acharam você às 7h. Rosa contou pra todo mundo. Virou história de família." } },
    ],
  },
  {
    cena: "garagem",
    titulo: "A aranha",
    texto: "Uma aranha do tamanho de uma mão entra andando como se pagasse aluguel. E talvez pague.",
    opcoes: [
      { texto: "Pote, papel, soltar no mato, ritual de gente evoluída", habilidade: "Sobrevivência selvagem",
        sucesso: { vida: +10, bateria: 0, frase: "Capturada com dignidade. Solta a 50 metros. Ela voltou no dia seguinte, mas isso é outra história." },
        falha:   { vida: -15, bateria: 0, frase: "Ela pulou. Você pulou. O pote quebrou. Ninguém sabe onde ela está agora." } },
      { texto: "Chinelada com precisão de atirador", habilidade: "Armas de fogo",
        sucesso: { vida: +10, bateria: 0, frase: "Um tiro, um alvo. O chinelo nunca mais foi o mesmo." },
        falha:   { vida: -10, bateria: 0, frase: "Errou. A aranha agora sabe quem você é." } },
      { texto: "Sair de fininho e chamar a Esther pra resolver", habilidade: "Sociabilidade",
        sucesso: { vida: 0, bateria: +5, frase: "Esther resolveu em 4 segundos com uma revista. Você segurou a lanterna." },
        falha:   { vida: 0, bateria: -20, frase: "Esther perguntou 'você não é o cara da sobrevivência selvagem?'. Não tinha resposta." } },
    ],
  },
  {
    cena: "casa",
    titulo: "A porta",
    texto: "A porta não abre. Não está trancada. Simplesmente decidiu que hoje não.",
    opcoes: [
      { texto: "Desmontar a fechadura e descobrir que era uma mola de 2 reais", habilidade: "Relojoaria",
        sucesso: { vida: +15, bateria: 0, frase: "Mola trocada, porta abrindo como nova. Guardou a mola velha de troféu." },
        falha:   { vida: -10, bateria: 0, frase: "Desmontou tudo. Sobrou uma peça. A porta agora não fecha." } },
      { texto: "Ombrada de filme de ação, orçamento de novela", habilidade: "Resiliência",
        sucesso: { vida: +10, bateria: 0, frase: "Abriu na primeira. Você fingiu que não doeu. Doeu." },
        falha:   { vida: -20, bateria: 0, frase: "A porta não se moveu. Seu ombro sim. Pra um lugar onde não devia." } },
      { texto: "Entrar pela janela com a naturalidade de quem faz isso sempre", habilidade: "Skate",
        sucesso: { vida: +10, bateria: 0, frase: "Entrou limpo, pousou de pé, abriu a porta por dentro. Ninguém viu. Pena." },
        falha:   { vida: -15, bateria: 0, frase: "Ficou preso na metade. Esther tirou foto antes de ajudar." } },
    ],
  },
  {
    cena: "casa",
    titulo: "O ombro",
    texto: "Esther dormiu na sala em cima do seu ombro. O braço já não existe. O celular está a 40 cm.",
    opcoes: [
      { texto: "Sair devagar trocando você por uma almofada, técnica ninja", habilidade: "Preparação",
        sucesso: { vida: 0, bateria: +20, frase: "Troca perfeita. Ela abraçou a almofada e sorriu. Você é livre." },
        falha:   { vida: 0, bateria: -5, frase: "Ela acordou no meio da troca. 'Que que cê tá fazendo?'. Nada, amor." } },
      { texto: "Ficar imóvel duas horas como estátua de praça", habilidade: "Resiliência",
        sucesso: { vida: 0, bateria: +10, frase: "Duas horas. Formigamento total. Mas ela acordou dizendo que dormiu maravilhosamente." },
        falha:   { vida: -10, bateria: 0, frase: "O braço adormeceu tanto que quando ela levantou você caiu pro lado." } },
      { texto: "Puxar o celular com o pé, dedão de macaco", habilidade: "Skate",
        sucesso: { vida: 0, bateria: +10, frase: "Dedão preciso. Celular na mão. Duas horas de vídeo de faca sem acordar ninguém." },
        falha:   { vida: 0, bateria: -15, frase: "Derrubou o celular no chão. Barulho. Ela acordou. 'Sério?'" } },
    ],
  },
  {
    cena: "forja",
    titulo: "Acabou a luz",
    texto: "Breu total. Alguém já gritou \"Irving!\" de algum cômodo, como se você fosse a companhia elétrica.",
    opcoes: [
      { texto: "Sacar a lanterna do bolso antes de alguém terminar de piscar", habilidade: "EDC (kit de bolso diário)",
        sucesso: { vida: 0, bateria: +15, frase: "Lanterna acesa em 0,4 segundos. Todo mundo olhou. Você fingiu que era normal." },
        falha:   { vida: 0, bateria: -5, frase: "A lanterna estava no outro short. O único dia." } },
      { texto: "Abrir o estoque: 14 lanternas, 9 power banks, uma pra cada cômodo e sobra", habilidade: "Preparação",
        sucesso: { vida: 0, bateria: +25, frase: "A casa virou um shopping. Vizinho ligou perguntando se sua luz não caiu." },
        falha:   { vida: 0, bateria: -5, frase: "Todas carregadas menos as 14 que você pegou primeiro." } },
      { texto: "Ir no quadro e brigar com o disjuntor", habilidade: "Elétrica residencial",
        sucesso: { vida: +15, bateria: 0, frase: "Disjuntor desarmado. Rearmou. Luz. Aplausos de um cômodo distante." },
        falha:   { vida: -15, bateria: 0, frase: "Não era o disjuntor. Era a rua toda. Tomou um choquinho de lembrança." } },
    ],
  },
  {
    cena: "casa",
    titulo: "A festa da vizinha",
    texto: "A mulher do português está dando festa com som que faz o vidro tremer. Sertanejo. Duas da manhã.",
    opcoes: [
      { texto: "Ativar o \"mecanismo eletrônico\" que derruba o bluetooth da caixa deles", habilidade: "Eletrônica",
        sucesso: { vida: 0, bateria: +25, frase: "Silêncio às 2h07. Eles acham que a caixa quebrou. Você dormiu como um bebê." },
        falha:   { vida: 0, bateria: -10, frase: "O mecanismo derrubou o seu wifi. O sertanejo continuou." } },
      { texto: "Protetor auricular e dormir como quem venceu", habilidade: "Preparação",
        sucesso: { vida: +15, bateria: 0, frase: "Acordou às 8h descansado. A festa acabou às 5h. Você não soube." },
        falha:   { vida: -5, bateria: 0, frase: "O protetor caiu de madrugada. Acordou no refrão." } },
      { texto: "Ir lá conversar de pijama, \"como bom vizinho\"", habilidade: "Sociabilidade",
        sucesso: { vida: 0, bateria: +5, frase: "Abaixaram um pouco. Te ofereceram cerveja. Você recusou e ficou 40 minutos mesmo assim." },
        falha:   { vida: 0, bateria: -30, frase: "Te puxaram pra dentro. Você cantou 'Evidências' com o português às 3h. Tem vídeo." } },
    ],
  },
  {
    cena: "casa",
    titulo: "A criança lobisomem",
    texto: "\"Temos que ver a criança lobisomem da Tainá.\" Você não sabe o que é isso. Ninguém explica. Todo mundo vai.",
    opcoes: [
      { texto: "Levar a câmera e fazer um documentário premiado", habilidade: "Fotografia",
        sucesso: { vida: 0, bateria: +15, frase: "Era uma peça de escola. Suas fotos ficaram tão boas que a Tainá chorou." },
        falha:   { vida: 0, bateria: -10, frase: "Flash ligado. A criança lobisomem chorou. O lobisomem tinha 6 anos." } },
      { texto: "Perguntar o que é a criança lobisomem e receber olhares", habilidade: "Sociabilidade",
        sucesso: { vida: 0, bateria: +10, frase: "Explicaram. Ainda não faz sentido, mas você sorriu no momento certo." },
        falha:   { vida: 0, bateria: -15, frase: "'Como assim você não sabe?'. Ninguém explicou. Você foi mesmo assim." } },
      { texto: "Ir com canivete no bolso, por precaução, lobisomem é lobisomem", habilidade: "Preparação",
        sucesso: { vida: +10, bateria: 0, frase: "Não precisou do canivete. Mas dormiu tranquilo sabendo que estava lá." },
        falha:   { vida: 0, bateria: -10, frase: "O detector de metais da escola apitou. Você explicou o EDC pra uma diretora." } },
    ],
  },
  {
    cena: "escritorio",
    titulo: "Amigo secreto do pilates",
    texto: "O pessoal do pilates quer fazer amigo secreto. Você foi duas vezes. Estão te contando como membro fundador.",
    opcoes: [
      { texto: "Não ir, não responder, deixar o grupo esquecer que você existe", habilidade: "Resiliência",
        sucesso: { vida: 0, bateria: +20, frase: "Silenciou o grupo. Em três dias ninguém lembrava do seu nome. Liberdade." },
        falha:   { vida: 0, bateria: -5, frase: "Te marcaram 11 vezes. Você tirou alguém que você nunca viu." } },
      { texto: "Forjar uma faca e virar o presente que ninguém supera", habilidade: "Cutelaria",
        sucesso: { vida: 0, bateria: +15, frase: "A instrutora ganhou uma faca forjada. Agora você é membro vitalício. Contra a vontade." },
        falha:   { vida: 0, bateria: -10, frase: "Teto era 30 reais. Sua faca vale 400. Constrangimento geral." } },
      { texto: "\"Eu não faço pilates\", dito pra quem te viu lá", habilidade: "Filosofia",
        sucesso: { vida: 0, bateria: +5, frase: "Argumentou que duas aulas não constituem prática. Aceitaram. Filosoficamente." },
        falha:   { vida: 0, bateria: -20, frase: "Mostraram a foto. Você de meia antiderrapante. Não tinha defesa." } },
    ],
  },
  {
    cena: "escritorio",
    titulo: "O show imperdível",
    texto: "Convite pra um show \"imperdível\": um menino paraguaio de 17 anos que toca música assobiando em garrafas de vidro.",
    opcoes: [
      { texto: "Não ir. Simplesmente não ir", habilidade: "Preparação",
        sucesso: { vida: 0, bateria: +15, frase: "Ficou em casa. Forjou. Ninguém sentiu sua falta e você não sentiu falta de ninguém." },
        falha:   { vida: 0, bateria: -5, frase: "Esther comprou o ingresso antes. Não reembolsável." } },
      { texto: "Ir, não gostar, e ter que fingir por 90 minutos", habilidade: "Resiliência",
        sucesso: { vida: 0, bateria: +10, frase: "Aplaudiu na hora certa. Disse 'interessante' três vezes. Sobreviveu." },
        falha:   { vida: 0, bateria: -20, frase: "Dormiu no bis. Roncou. O menino parou de assobiar." } },
      { texto: "Se perguntar em voz alta quem em sã consciência vai nisso", habilidade: "Filosofia",
        sucesso: { vida: 0, bateria: +10, frase: "A pergunta ficou no ar. Ninguém respondeu. Ninguém foi." },
        falha:   { vida: 0, bateria: -25, frase: "A mãe do menino estava atrás de você." } },
    ],
  },
  {
    cena: "quintal",
    titulo: "O cavalo",
    texto: "Você foi ver o cavalo. Ele te olhou, bufou e virou a bunda. Ele não é seu fã e não esconde.",
    opcoes: [
      { texto: "Cenoura, paciência e ego no bolso", habilidade: "Criação de animais",
        sucesso: { vida: 0, bateria: +15, frase: "Comeu a cenoura. Deixou passar a mão. Um progresso diplomático histórico." },
        falha:   { vida: -15, bateria: 0, frase: "Comeu a cenoura e mordeu o dedo junto. Ele avisou." } },
      { texto: "Montar mesmo assim, na confiança de quem pilota moto", habilidade: "Pilotagem de moto",
        sucesso: { vida: +20, bateria: 0, frase: "Montou. Trotou. O cavalo ficou impressionado. Você também." },
        falha:   { vida: -25, bateria: 0, frase: "Três segundos no lombo. Pouso no cocho. O cavalo relinchou. Era riso." } },
      { texto: "Foto de longe e legenda \"ele posou pra mim\"", habilidade: "Fotografia",
        sucesso: { vida: 0, bateria: +10, frase: "A foto ficou linda. 200 curtidas. Ninguém sabe que era a bunda." },
        falha:   { vida: 0, bateria: -5, frase: "Esther comentou: 'ele tá de costas'." } },
    ],
  },
  {
    cena: "quintal",
    titulo: "As galinhas fugiram",
    texto: "As duas galinhas estão no telhado. Ninguém sabe como. Elas parecem orgulhosas.",
    opcoes: [
      { texto: "Escada e negociação com ave", habilidade: "Criação de animais",
        sucesso: { vida: +10, bateria: 0, frase: "Desceram com milho e conversa. Uma delas pareceu pedir desculpa." },
        falha:   { vida: -20, bateria: 0, frase: "Uma voou na sua cara. Você caiu no degrau 3. A escada tem 4." } },
      { texto: "Esperar, fome é o melhor negociador", habilidade: "Filosofia",
        sucesso: { vida: +10, bateria: 0, frase: "Às 18h desceram sozinhas. Você fingiu que foi estratégia. Foi." },
        falha:   { vida: 0, bateria: -10, frase: "Elas dormiram no telhado. Esther perguntou se você ia fazer alguma coisa." } },
      { texto: "Skate, cabo de vassoura e nenhum plano", habilidade: "Skate",
        sucesso: { vida: +15, bateria: 0, frase: "Não faz sentido, mas funcionou. Galinhas no chão, você no skate, o cabo no telhado." },
        falha:   { vida: -20, bateria: 0, frase: "O plano não tinha etapa 2. O cabo caiu na calha. Você caiu no skate." } },
    ],
  },
  {
    cena: "escritorio",
    titulo: "O Rolex do amigo",
    texto: "O João apareceu com um \"Rolex\" de 200 reais e quer sua opinião sincera. Ele está muito feliz.",
    opcoes: [
      { texto: "Abrir a tampa e ver o mecanismo fazer \"tec\"", habilidade: "Relojoaria",
        sucesso: { vida: 0, bateria: +10, frase: "Abriu, olhou, fechou. 'Funciona'. Tecnicamente verdade. Ele ficou feliz." },
        falha:   { vida: 0, bateria: -15, frase: "Abriu e o ponteiro caiu. Agora é um Rolex de 200 reais quebrado. Por sua culpa." } },
      { texto: "\"Ficou lindo em você\", com o coração pesado", habilidade: "Sociabilidade",
        sucesso: { vida: 0, bateria: +15, frase: "Ele sorriu por três dias. Você carrega esse peso." },
        falha:   { vida: 0, bateria: -10, frase: "Sua cara não acompanhou a frase. Ele percebeu. Ficou triste em dois idiomas." } },
      { texto: "Aula de 20 minutos sobre falsificação suíça", habilidade: "Filosofia",
        sucesso: { vida: 0, bateria: +5, frase: "Ele ouviu tudo, agradeceu, e continuou usando. Vitória moral, derrota prática." },
        falha:   { vida: 0, bateria: -25, frase: "Ele tirou o relógio no minuto 8 e foi embora no minuto 9." } },
    ],
  },
  {
    cena: "forja",
    titulo: "O churrasqueiro",
    texto: "O primo da Esther faz o pior churrasco da família. Carne cinza, sal em cubo. Ele insiste que hoje é ele. Já está de avental.",
    opcoes: [
      { texto: "Assumir a grelha \"só pra ajudar\" e nunca devolver", habilidade: "Culinária",
        sucesso: { vida: 0, bateria: +20, frase: "'Deixa que eu viro essa aqui'. Duas horas depois ele estava de espectador. A carne, perfeita." },
        falha:   { vida: 0, bateria: -15, frase: "Ele percebeu o golpe. Cruzou os braços. Você comeu carne cinza sorrindo." } },
      { texto: "Elogiar a carne cinza com olhos marejados", habilidade: "Sociabilidade",
        sucesso: { vida: 0, bateria: +10, frase: "'Tá no ponto!'. Ele acreditou. Esther não. Mas Esther não conta." },
        falha:   { vida: 0, bateria: -20, frase: "Você disse 'tá bom' com a voz de quem está mentindo. Ele ouviu. A família ouviu." } },
      { texto: "Fazer um churrasco paralelo na forja e chamar de \"degustação\"", habilidade: "Cutelaria",
        sucesso: { vida: +20, bateria: 0, frase: "A degustação virou o churrasco. O primo ficou com a churrasqueira e ninguém." },
        falha:   { vida: 0, bateria: -15, frase: "Fumaça demais. Alarme. Bombeiro perguntou por que tem duas churrasqueiras." } },
    ],
  },
  {
    cena: "casa",
    titulo: "A placa da entrada",
    texto: "A placa de madeira do antigo dono caiu. Esther diz que é sinal pra fazer a nova. Hoje. Agora.",
    opcoes: [
      { texto: "Entalhar uma nova na hora, com direito a assinatura", habilidade: "Pintura",
        sucesso: { vida: 0, bateria: +15, frase: "Ficou linda. Esther postou. Três vizinhos pediram uma." },
        falha:   { vida: 0, bateria: -10, frase: "Errou a letra. A casa agora se chama 'Fortalesa'." } },
      { texto: "Soldar um suporte que sobrevive a um tornado", habilidade: "Solda",
        sucesso: { vida: +15, bateria: 0, frase: "Suporte de aço 6 mm. A casa cai antes da placa." },
        falha:   { vida: -15, bateria: 0, frase: "Queimou a manga. E a placa. Agora não tem placa nem manga." } },
      { texto: "Fita adesiva e \"semana que vem eu faço\"", habilidade: "Negociação",
        sucesso: { vida: 0, bateria: +5, frase: "Negociou prazo de 7 dias. Foram 47. A fita aguentou." },
        falha:   { vida: 0, bateria: -20, frase: "Esther anotou a data. Ela anota tudo." } },
    ],
  },
];
